### ISSUE TITLE
Loading cardinalities from CIM SSP

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#108]
@martinnec prepares SPARQL queries
@sstenchlak implements them

**Comment by martinnec** [comment]
Sample SPARQL query for loading the cardinality of a CIM attribute associated with a CIM class in SSP:

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?min ?max
WHERE {
  <https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl> a owl:Class .
  OPTIONAL {
    <https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl> rdfs:subClassOf [
		a owl:Restriction ;
		owl:onProperty <https://slovník.gov.cz/základní/pojem/má-vlastnost> ;
  		owl:onClass <https://slovník.gov.cz/datový/turistické-cíle/pojem/kouření-povoleno> ;
 		owl:maxQualifiedCardinality ?max
  	] .
  }
  OPTIONAL {
	<https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl> rdfs:subClassOf [
		a owl:Restriction ;
		owl:onProperty <https://slovník.gov.cz/základní/pojem/má-vlastnost> ;
  		owl:onClass <https://slovník.gov.cz/datový/turistické-cíle/pojem/kouření-povoleno> ;
 		owl:minQualifiedCardinality ?min
  	] .
  }
}
```

**Comment by sstenchlak** [comment]
Can you please check whether the query for the association is correct?
https://github.com/opendata-mvcr/model-driven-data/blob/f22c39de3bbc6bd3bbf492c806cad1aea25eadae/packages/core/src/sgov/queries/get-surroundings-outwards-relations.sparql#L59-L93

I was not sure how to implement this for complex attributes. Should it be the same as for simple attributes?

Also, it seems that many attributes have cardinality defined in exactly the opposite way than you do. For example, the following one. Is this correct? Because I was unable to find the other direction.
```ttl
<https://slovník.gov.cz/datový/registr-silničních-vozidel/pojem/datum-platnosti-technické-prohlídky-od> rdfs:subClassOf _:b2748571 .
_:b2748571 rdf:type owl:Restriction ;
 owl:onProperty <https://slovník.gov.cz/základní/pojem/je-vlastností> ;
 owl:maxQualifiedCardinality	"1"^^xsd:nonNegativeInteger ;
 owl:onClass	<https://slovník.gov.cz/legislativní/sbírka/56/2001/pojem/technická-prohlídka> .
```

**Comment by martinnec** [comment]
The previous should be:

```
    	OPTIONAL {
    	?domainElement rdfs:subClassOf [
			a owl:Restriction ;
			owl:onProperty [
        		owl:inverseOf <https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-1> 
    		];
  			owl:onClass ?outwardsRelation ;
 			owl:minQualifiedCardinality ?range_min
  	  	] .
	}
    OPTIONAL {
    	?domainElement rdfs:subClassOf [
			a owl:Restriction ;
			owl:onProperty [
        		owl:inverseOf <https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-1> 
    		];
  			owl:onClass ?outwardsRelation ;
 			owl:maxQualifiedCardinality ?range_max
  	  	] .
	}
    OPTIONAL {
    	?rangeElement rdfs:subClassOf [
			a owl:Restriction ;
			owl:onProperty [
        		owl:inverseOf <https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-2> 
    		];
  			owl:onClass ?outwardsRelation ;
 			owl:minQualifiedCardinality ?domain_min
  	  	] .
	}
	OPTIONAL {
    	?rangeElement rdfs:subClassOf [
			a owl:Restriction ;
			owl:onProperty [
        		owl:inverseOf <https://slovník.gov.cz/základní/pojem/má-vztažený-prvek-2> 
    		];
  			owl:onClass ?outwardsRelation ;
 			owl:maxQualifiedCardinality ?domain_max
  	  	] .
	}
```

**Comment by martinnec** [comment]
SSP is expressed in OWL. Here, max cardinalities "\*" are expressed by not specifying them at all. I.e. unspecified max cardinalities shall be interpreted as "\*". Min cardinalities "0" can be expressed either by explicit specification of "0" or by not specifying them at all. I.e. unspecified min cardinalities shall be interpreted as "0".

**Comment by sstenchlak** [comment]
@martinnec currently there are following queries for cardinalities:

- In both directions for [attributes](https://github.com/opendata-mvcr/model-driven-data/blob/7a7cee62e3dbd78904028b4119e1a5d79e7f3613/packages/core/src/sgov/queries/get-surroundings-attributes.sparql#L56-L92).
- In the single direction (that you provided) for [relations](https://github.com/opendata-mvcr/model-driven-data/blob/7a7cee62e3dbd78904028b4119e1a5d79e7f3613/packages/core/src/sgov/queries/get-surroundings-outwards-relations.sparql#L60-L100) and [inwards relations](https://github.com/opendata-mvcr/model-driven-data/blob/7a7cee62e3dbd78904028b4119e1a5d79e7f3613/packages/core/src/sgov/queries/get-surroundings-inwards-relations.sparql#L57-L97). **There are no queries for the other direction as you said it is not currently in use.**
- **There is no cardinality query for complex attributes.**

**Comment by martinnec** [comment]
@sstenchlak there is one mistake in the query (I specified it incorrectly at the start of the issue)

The [query](https://github.com/opendata-mvcr/model-driven-data/blob/7a7cee62e3dbd78904028b4119e1a5d79e7f3613/packages/core/src/sgov/queries/get-surroundings-attributes.sparql#L75) for one of the directions is incorrect. We have

```
    OPTIONAL {
        ?attribute rdfs:subClassOf [
            a owl:Restriction ;
            owl:onProperty <https://slovník.gov.cz/základní/pojem/je-vlastností> ;
            owl:onClass %NODE% ;
            owl:maxQualifiedCardinality ?max
        ] .
    }

    OPTIONAL {
        ?attribute rdfs:subClassOf [
            a owl:Restriction ;
            owl:onProperty <https://slovník.gov.cz/základní/pojem/je-vlastností> ;
            owl:onClass %NODE% ;
            owl:minQualifiedCardinality ?min
        ] .
    }
```

but it should be

```
    OPTIONAL {
        %NODE% rdfs:subClassOf [
            a owl:Restriction ;
            owl:onProperty [
              owl:inverseOf <https://slovník.gov.cz/základní/pojem/je-vlastností>
            ] ;
            owl:onClass ?attribute ;
            owl:maxQualifiedCardinality ?max
        ] .
    }

    OPTIONAL {
        %NODE% rdfs:subClassOf [
            a owl:Restriction ;
            owl:onProperty [
              owl:inverseOf <https://slovník.gov.cz/základní/pojem/je-vlastností>
            ] ;
            owl:onClass ?attribute ;
            owl:minQualifiedCardinality ?min
        ] .
    }
```
