### ISSUE TITLE
Use xs:group for non-materialized properties

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/dataspecer#109]
Based on #97 we now have property ```isNotMaterialized``` on a property. If set to true, the class of the association should be represented using ``` xs:group```.

**Comment by jakubklimek** [comment]
Actually, this use case does not require the usage of `xs:group` as there is no reuse of the group. Until we find a usecase where the group is actually reused, we can implement this just by the simple inclusion of the content of the child into the content of the parent.
