### ISSUE TITLE
Thread save operations

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/dataspecer#11]
Although JS code runs in a single thread it is possible to call a single function multiple times using ```async```/```wait ```and ```Promises```. This can be problem for the ```CoreModelWriter``` as we do not support running of multiple operations simultaneously.  This must be at least document so the user is aware of this.

In addition we may try to introduce some mechanism that would make sure that operations are evaluated one at a time. We just nee to keep in mind, that the Store, implementing the ````CoreModelWriter``` may be on a server. So the functionality may need to be close to the store.

**Comment by sstenchlak** [comment]
A backend service will address this. It will serve as a "transaction processing system"
