### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#118]
I propose the following structure of the documentation:

# Conceptual model

> PlantUML diagram of PIM (only parts used in PSMs)

## [PIM class name] (for each PIM class used in PSMs)

[PIM class description]

### [PIM attribute name] (for each PIM attribute with [PIM class] as its domain)

- Typ: [PIM attribute type]
- Popis: [PIM attribute description]
- Povinnost: (Povinná when [min cardinality] > 0, Nepovinná when [min cardinality] == 0
- Význam: Význam vlastnosti [PIM attribute name] je v sémantickém slovníku pojmů definován jako [CIM attribute name] as [link](https://slovník.gov.cz/prohlížíme/) to [CIM attribute]

### Vztah: [PIM association name] (for each PIM association with [PIM class] as its domain)

- Typ: [range PIM class name] as link to [PIM class] in this specification
- Popis: [PIM association description]
- Povinnost: (Povinná when [min cardinality] > 0, Nepovinná when [min cardinality] == 0
- Význam: Význam vztahu [PIM association name] je v sémantickém slovníku pojmů definován jako [CIM association name] as [link](https://slovník.gov.cz/prohlížíme/) to [CIM association]

# [Data structure name] (for each data structure in the data specification)

[Data structure description]

### [PSM class name] (for each PSM class used in the PSM of the data structure in deep-first-search starting in the root)

- Popis: [PSM class description]

#### [PSM attribute name] (for each PSM attribute of the [PSM class]

- Key/element/column/...: [PSM attribute technical label] (depends on the format)
- Typ: [PSM attribute type]
- Popis: [PSM attribute description]
- Povinnost: (Povinná when [min cardinality] > 0, Nepovinná when [min cardinality] == 0
- Význam: Vlastnost [PSM attribute name] odpovídá v konceptuálním modelu vlastnosti [PIM attribute name] as link to the above section for the [PIM attribute]

#### Vztah: [PSM association name] (for each PSM association of the [PSM class])

- Key/element/column/...: [PSM association technical label] (depends on the format)
- Typ: [target PSM class name] as link to [PSM class] in this specification
- Popis: [PSM association description]
- Povinnost: (Povinná when [min cardinality] > 0, Nepovinná when [min cardinality] == 0
- Význam: Vztah [PSM association name] odpovídá v konceptuálním modelu vztahu [PIM association name] as link to the above section for the [PIM association]

**Comment by skodapetr** [comment]
Should a schema, e.g. XSD, JsonSchema, be included directly in the documentation or should there be a link?

**Comment by jakubklimek** [comment]
I would also consider "Vícečetnost" - so that we have both cardinality values in the description of a PIM/PSM attribute/association. I know I do not have it in the current FOSes, but it should be there I think.

As to the schema, I would just link it. I view it as just a machine readable version of the PSM documentation, in contrast to examples, which I would include.

**Comment by skodapetr** [comment]
@jakubklimek  What is the meaning of "Vícečetnost" ?

**Comment by jakubklimek** [comment]
0..1/1..1 vs 0..n/1..n

**Comment by skodapetr** [comment]
We still have this as a cardinality, so I would naturally vote to preserve it. But that may be better to discuss with a particular example.

**Comment by jakubklimek** [comment]
Sure, what I meant was that now we have "Povinnost", but that is only one half of the cardinality
