### ISSUE TITLE
Support for XML namespaces

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#127]
In FOSes, we use XML namespaces to separate element definitions from individual FOSes.
We need to add support for XML namespaces in model-driven-data.
I suggest adding the possibility of specifying XML namespace (and its preferred prefix) for each PSM. This would become the `targetNamespace` of the generated XML schema. The preferred prefixes would be used both in the generated schema and in the XML schemas importing it.

This includes changing the "elementFormDefault" to "qualified".

**Comment by cermakmarek** [comment]
That should not be an issue; there is already some support of a namespace in the `XmlSchema` model, so all I would need is the presence of this information on the `StructureModel` object.
