### ISSUE TITLE
Checking PSM/PIM cardinalities w.r.t. CIM cardinalities

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#133]
When I create PIM/PSM from CIM, cardinalities are materialized in PIM. When cardinalities in the source of the CIM change, I cannot see this change in PIM/PSM. I propose to add a feature which allows me to check whether the cardinalities have changed. However, we are not able to recognize whether they changed in CIM because we do not remember them. It should be enough to have a feature which compares PIM cardinalities to the source cardinalities in CIM and it shows that there is a difference to the user. This difference can be shown on the detail of a PSM element. We can also add a button in the detail of a data specification and/or PSM schema which shows me the list of differences. The comparison cannot be done continuously in regular intervals or too often as it could be costly. I think it should be enough to compute the comparison in these events:
- the user opens the detail of the data specification
- the user clicks on the button for showing the differences

**Comment by sstenchlak** [comment]
This is a generic problem of comparing different "versions" of conceptual models. This will be addressed in evolution.
