### ISSUE TITLE
Specialization of StructureModel

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/dataspecer#167]
It was decided that data-psm will have specializations for xml, json, ... where each specialization will add entry to the *extension* property. The entry would contains the added data for particular view on the PSM. 

This should be reflected in the Structure model as well. The structure model should be extended for particular formats giving us XmlStrcutureModel or JsonStructureModel. Generators should employ only this model to read information from, they should not directly interact with PIM or PSM. 

There is open question however what should be the Structure model. As the current model may be only one possible alternative, focused on entities. 

It is also not clear how this model should be loaded whether format (XML, JSON, .. ) specific code should have the ability to hook into loader or should be given instance of structure model and be responsible to transform it to specific model.

**Comment by sstenchlak** [comment]
So far only XML specialization is available.

- XML structure model classes extend structure model classes and add their own properties. ceb1536943c4003bdd090e5f8206975ca54aa7db
- All data psm resources extend [`ExtendableCoreResource`](https://github.com/mff-uk/dataspecer/blob/37a0a2dbe42014569496ccaf6d53b695cb46457b/packages/core/src/data-psm/model/extendable-core-resource.ts) and XML schema was introduced with a method for easier access to extension data. 0985a5aaac24801391ac0b66b0968d78b1c042d9
