### ISSUE TITLE
"titles" in CSVW descriptor should contain technical label, not human readable name

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#197]
e.g. in this column description:
```json
{
    "@type": "Column",
    "name": "is_public",
    "titles": {
        "en": "public accessibility"
    },
    "propertyUrl": "https://slovník.gov.cz/datový/turistické-cíle/pojem/veřejná-přístupnost",
    "valueUrl": null,
    "dc:description": {
        "@value": "Determines whether the tourist destination is publicly accessible. ",
        "@lang": "en"
    },
    "datatype": "boolean",
    "lang": "cs",
    "required": false,
    "virtual": false
}
```

we should have the technical label as "titles" - i.e. the actual column name in the CSV, and the name from the model in "dc:title" - metadata.:
```json
{
    "@type": "Column",
    "name": "is_public",
    "titles": "is_public",
    "propertyUrl": "https://slovník.gov.cz/datový/turistické-cíle/pojem/veřejná-přístupnost",
    "valueUrl": null,
    "dc:title": {
        "en": "public accessibility"
    },
    "dc:description": {
        "@value": "Determines whether the tourist destination is publicly accessible. ",
        "@lang": "en"
    },
    "datatype": "boolean",
    "lang": "cs",
    "required": false,
    "virtual": false
}
```

**Comment by JanJanda** [comment]
The specification (https://www.w3.org/TR/tabular-data-primer/#multilingual-metadata) describes different syntax for multilingual metadata. I will use it instead of the standard language map which you suggest. Do you have any special reason for language map?

**Comment by jakubklimek** [comment]
Originally, I wanted to say that the CSVW descriptor is a JSON-LD file with the context https://www.w3.org/ns/csvw.jsonld. In that context, `dc:description` is defined as a language map. However, it is defined there only in the context of the data contained in that file (it is not only context). For usage in CSVW descriptors, it is indeed necessary to not use the JSON-LD language map, as there is no definition of `dc:description` in the context.

However, the example in the primer is wrong anyway, see the RDF triples coming out of the descriptor in JSON-LD playground. It needs to be `@language`, not `@lang`.
