### ISSUE TITLE
When reusing schema with namespace, use xs:import instead of xs:include

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#222]
When a referenced specification uses a namespace, its XSD needs to be imported instead of included, and its namespace must be introduced to the importing schema, so that it can be used in references.

See [this example](https://a55e919d.dataspecer.pages.dev/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F37aaf868-c462-4639-8117-64723d92796e) - The tourist destination references Barrier-free access, which has a namespace. However, the link does not work, as the namespace is not defined in the tourist destination XSD, and the schema is included instead of imported (you specify the namespace of the imported schema with xs:import).

**Comment by cermakmarek** [comment]
Yes, the code to generate `<xs:import>` is there already, but it is not yet taken from the reused artifact.

@sstenchlak Is it possible to retrieve the XML extension from a `DataSpecificationArtefact`.
