### ISSUE TITLE
Generated SPARQL query does not contain specific type

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#254]
e.g. [here](https://tool.dataspecer.com/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F43993f16-e793-4752-ac83-f06aa20755fe&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1643204276321-9b46-c2aa-a1b0)
![image](https://user-images.githubusercontent.com/718827/204746467-4fab1a4f-3a47-4d30-9a3e-5e23547b2d49.png)
The query is:
```sparql
PREFIX ns1: <https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/>
PREFIX ns2: <https://slovník.gov.cz/generický/umístění/pojem/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?název ?má_sídlo_právnické_osoby_má_místo_sídla_má_zahraniční_adresu_lokalizační_popis
WHERE {
  OPTIONAL {
    ?cs ns1:název-právnické-osoby ?název .
  }
  OPTIONAL {
    ?cs ns2:lokalizační-popis ?má_sídlo_právnické_osoby_má_místo_sídla_má_zahraniční_adresu_lokalizační_popis .
  }
  ?cs rdf:type ?v1 .
}
```

I would expect the type to be `https://slovník.gov.cz/legislativní/sbírka/89/2012/pojem/zahraniční-právnická-osoba` instead of `?v1`, which would match any type, not just the one corresponding to the spec.

**Comment by JanJanda** [comment]
Solved as part of #256.
