### ISSUE TITLE
Missing label of backwards association

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#263]
In "modifications", I have:
```turtle
#Missing in RDF vocab definitions
m8g:identifies rdfs:label "identifies"@en .
```
supplementing the definition from the original vocabulary `legal`:
```turtle
<https://data.europa.eu/m8g/identifies> a owl:ObjectProperty;
  rdfs:domain <http://www.w3.org/ns/adms#Identifier>;
  rdfs:isDefinedBy <https://data.europa.eu/m8g>;
  rdfs:range <http://www.w3.org/ns/legal#LegalEntity> .
```
However, in Dataspecer, I still see the association as "no title":
![image](https://user-images.githubusercontent.com/718827/206996954-7e3a24c6-0712-434e-b02b-6c2ea4f3c6c1.png)

Maybe this is caused by inability to take parts of the definitions from different files?

**Comment by sstenchlak** [comment]
Hi, the property IRIs have different schemas - one has http and one https.

**Comment by jakubklimek** [comment]
Good catch, passed [upstream](https://github.com/SEMICeu/Core-Business-Vocabulary/issues/41).
