### ISSUE TITLE
For single-table CSV schema, a naming convention should be followed

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#264]
Now, in case of a single-table CSV and schema, I get:
```json
"@id": "https://ofn.gov.cz/schema/ofn-lide-a-osoby/43993f16-e793-4752-ac83-f06aa20755fe/schema.csv-metadata.json",
"url": "https://ofn.gov.cz/schema/ofn-lide-a-osoby/43993f16-e793-4752-ac83-f06aa20755fe/schema.csv-metadata.json/table.csv",
```
However, the correct naming convention is `x.csv` and `x.csv-metadata.json`

Even though we do not have any actual data at the moment, I would consider changing these to:
```json
"@id": "https://ofn.gov.cz/schema/ofn-lide-a-osoby/43993f16-e793-4752-ac83-f06aa20755fe/table.csv-metadata.json",
"url": "table.csv",
```
The relative `url` allows usage of the schema even locally, in the file system, with "table".

**Comment by JanJanda** [comment]
I also added a similar id to multi-table schema for uniformity.
