### ISSUE TITLE
Cannot open specification (JSON SyntaxError)

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#267]
When trying to open [this specification](https://feature-cim-adapters-and-rdf.dataspecer.pages.dev/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F9b8dd594-4fc2-44fc-98c8-90d7da94b04e&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1671088481211-edb7-46c0-b8f8) I get a syntax error:

![image](https://user-images.githubusercontent.com/718827/207838968-0775e7fd-ab73-4733-aa1f-b4f3cd55b92a.png)

**Comment by jakubklimek** [comment]
I also cannot list the structure:
![image](https://user-images.githubusercontent.com/718827/207839605-7c170ad1-2a7b-499c-997d-b94e03361a78.png)

What I did was set datatype to `Text` and multiplicity to `1`

**Comment by sstenchlak** [comment]
The error was caused by a still-existing #243 bug. Sorry. I have fixed the corrupted specification, and I will fix the bug soon.
