### ISSUE TITLE
Terminology: Conceptual model sources?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#281]
Is "Conceptual model sources" the correct term?
![image](https://user-images.githubusercontent.com/718827/210503448-4cf48bfc-450f-4c8d-99c2-81e70ef98a26.png)

Shouldn't it be something else, like
- "Vocabulary sources"
- "Source vocabularies"
- "Ontology sources"
- ...?

**Comment by martinnec** [comment]
Yes, I vote for Vocabulary sources
