### ISSUE TITLE
Attributes from child classes?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#289]
When looking at a possible content of Turistický cíl, I can see attributes of other classes listed there, specifically - "kapacita" from Sportoviště. I am not sure why:
![image](https://user-images.githubusercontent.com/718827/220334922-c9d80695-5c86-476e-95ef-a40b113d7f4f.png)

**Comment by sstenchlak** [comment]
It seems that DS works correctly.

`https://slovník.gov.cz/datový/sportoviště/pojem/kapacita` is an attribute of `https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl` through `nodeID://b4180020`. See:

https://github.com/opendata-mvcr/ssp/blob/df43cac5fddb6a015f15104baffd0ae76a064a0d/content/vocabularies/d-sgov-turistick%C3%A9-c%C3%ADle/d-sgov-turistick%C3%A9-c%C3%ADle-model.ttl#L168

**Comment by jakubklimek** [comment]
Hmmm... and I already have an issue on that https://github.com/opendata-mvcr/ssp/issues/462
