### ISSUE TITLE
PlantUML generated diagram is cropped

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#297]
E.g. in [this specification](https://xn--slovnk-7va.gov.cz/generujeme/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F3efaf255-aec8-45d2-872e-5033cbabc354)
Like this:
![conceptual-model](https://user-images.githubusercontent.com/718827/222712861-d8cb08c3-254a-43ed-8635-7728bdab3bd1.png)

**Comment by sstenchlak** [comment]
Hi, I needed to change the image type from PNG to SVG as the PlantUML generator has limitations to image size.

The SVG variant seems to work (including the final documentation).
