### ISSUE TITLE
After changing @type key mapping back to human readable, it is just an IRI

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#299]
```json
{
  "@context": {
    "@version": 1.1,
    "id": "@id",
    "type": "@type",
    "@base": "https://rpp-opendata.egon.gov.cz/odrpp/zdroj/",
    "položky": "@graph",
    "https://ofn.gov.cz/class/1657559419870-0fbe-aa7c-b6fd": {
      "@id": "https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/orgán-veřejné-moci",
      "@context": {
        "identifikátor": {
```

**Comment by sstenchlak** [comment]
I am sorry, I was unable to reproduce this issue.

IRI is used:

- if you select a **human label** as `@type`, but there is no human label at all. (this should not be our case)
- if you somehow select an option other than a human label or technical label, which should not be possible from UI.

**Comment by jakubklimek** [comment]
![label](https://user-images.githubusercontent.com/718827/224264284-72982e52-0871-4327-9bc7-6bbdafe91975.gif)
