### ISSUE TITLE
Regular expressions make sense also for IRIs

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#301]
Regular expressions in JSON Schema make sense also for IRI data types (generally, all JSON String-based data types).

```json
"využívá": {
            "type": "array",
            "items": {
              "title": "využívá veřejné údaje",
              "type": "string",
              "format": "iri",
              "pattern": "^údaj/[0-9]+-[0-9]+-[0-9]+$"
            }
          }
```

**Comment by sstenchlak** [comment]
This was already implemented at the time. Maybe the problem is #302.

**Comment by jakubklimek** [comment]
Not really. We are not talking about attributes here (there it works).
We are talking about associations, e.g.:
![image](https://user-images.githubusercontent.com/718827/224262488-d087cdb5-c099-4cf5-86c8-d812a1a6e568.png)
Here we are basically talking about specifying IRI pattern of instances of classes (and using it in JSON Schema wherever we repsresent a link to the class instance).
