### ISSUE TITLE
Allow choice of "generated artifacts"

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#308]
Right now, Generate artifacts generates everything. However, in cases where we only want to generate e.g. JSON Schema & JSON-LD contexts and have only the JSON part documented in bikeshed, this is insufficient.

This may have two levels
1. allow configuration of the bikeshed generator to only generate certain parts of the documentation - like this, the user can just pick the wanted artifacts
2. in bikeshed, include only documentation of artifacts configured to be generated, i.e. when only JSON artifacts are generated, include only JSON documentation, etc.

**Comment by jakubklimek** [comment]
I tried generating only JSON, PlantUML and Bikeshed in [this specification](https://xn--slovnk-7va.gov.cz/generujeme/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F3efaf255-aec8-45d2-872e-5033cbabc354). However, also other artifacts were generated. In the main specification, the core XML Schema file `2022-07.xsd` was included. In the reused specifications, all artifacts were included.

I think that the setting should be followed also for the reused specifications.

**Comment by sstenchlak** [comment]
Hi, I sort of implemented what you asked.

The configure artifacts button still works the same. It only configures the data specification that it belongs to. But from the screen with a list of specifications, it is now possible to change the default configuration before generating.

Setting the default configuration for each instance during the build is also possible.

![image](https://user-images.githubusercontent.com/23003372/230594007-f6a8a8b6-2e5e-4114-a64b-09c5ed847faa.png)

![image](https://user-images.githubusercontent.com/23003372/230594113-5844cb0d-7d23-42a6-b8da-c098bcfa234d.png)
