### ISSUE TITLE
Support for non-generated parts of documentation

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#311]
Currently we are lacking support for adding non-generated, i.e. human written, parts for the documentation, including some front matter, abstract, etc,.
See e.g. for comparison:
![image](https://user-images.githubusercontent.com/718827/226337812-6b9aaf0f-521a-4c6d-a9ae-ac544de2b3ce.png)

We need to think about how we could best support the inclusion of these texts and items into the specification, as rewriting those by hand every time a specification is updated is quite annoying.

I think we need at least:

1. URL of the current version
2. URL of the previous version
3. List of editors (name, organization, e-mail)
4. Links to GitHub based on base repo URL - link, new issue, list of commits, list of pull requests
5. Some generic links (POD, contact e-mail)
6. "Thanks" to grants
7. Abstract

**Comment by jakubklimek** [comment]
Support for 1-5 is there, 6 & 7 is still to be done

**Comment by sstenchlak** [comment]
- 1-5 can be configured as additional metadata.
- 7 Abstract is configurable directly in the UI.
- 6 Thanks - I need more details on what you mean by that.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/23003372/228977686-37b4c406-6351-4537-91a3-dd6ac5c692ae.png">

**Comment by sstenchlak** [comment]
Already resolved. Please open new issues if you have a problem with any particular part.
