### ISSUE TITLE
Nahrazené reference ve specifikaci nemají masku na regulární výraz

### ISSUE THREAD

**Issue by trusinas** [mff-uk/dataspecer#319]
Pokud si nastavím "Přepoužité datové specifikace" a následně je nahradím, ve vygenerovaném JSON schématu chybí klíč "pattern".
Např. https://slovník.gov.cz/generujeme/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2Fb9022208-52e3-4587-94a9-f131802d1142 - Datová schránka (datová-schránka).

**Comment by sstenchlak** [comment]
Jak se nasadí nová verze, mělo by už fungovat. Byla tam ještě jedna chyba, která bránila některým dalším informacím dostat se do JSON Schématu. Možná tedy bude výsledné schéma tímto bohatší.
