### ISSUE TITLE
Datatypes used in SHACL are not XSD-based

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#326]
SHACL validators understand and validate the typical XSD-based datatypes plus `rdf:langString`. The SHACL shapes now contain types from Czech standards, e.g. `https://ofn.gov.cz/zdroj/základní-datové-typy/2020-07-01/text`, which will not be understood by SHACL validators. There is a mapping of those to XSD-based types in the standards, which can be used. E.g. JSON Schema generators have their own mappings to JSON Schema types as well, as do the XML Schema generators.

**Comment by jakubklimek** [comment]
Actually, they are XSD-based in [this specification](https://tool.dataspecer.com/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2Fc39dbe3c-643b-4e97-9497-50d0ae6c371a&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1642618343791-8c0a-2ea2-b8d9) and not XSD-based in [this specification](https://tool.dataspecer.com/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F43993f16-e793-4752-ac83-f06aa20755fe&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1643204087643-0627-5e1b-a24e), which is quite confusing.

**Comment by LadyMalande** [comment]
Mapping added to the generator. Closing the issue.
