### ISSUE TITLE
Shouldn't the property shapes be also identified by IRIs?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#328]
Currently, property shapes of a Node shape are blank nodes, not identified by IRIs. This might have an effect on the usability of the resulting validation reports. We should consider pro's and con's of assigning IRIs also to property shapes.

**Comment by LadyMalande** [comment]
Added creation of property nodes for all properties. There are no more blank nodes in the generated turtle. Closing the issue.
