### ISSUE TITLE
IRIs of SHACL shapes

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#329]
Currently, IRIs of SHACL shapes seem to be constructed from the human readable label and IRI of a class, which is somehow converted to `Snake_case` and `Shape` is added, e.g. `https://slovník.gov.cz/generický/čas/pojem/Časový_intervalShape` based on `Časový interval`. There should be a discussion of considered alternatives and edge cases (possible naming conflicts), especially in cases where we have two data structures with different specifications for the same class, e.g. a less detailed data structure of Tourist destination and a more detailed structure of Tourist destination. In this case, both shapes would get the same IRI, which is not desirable.

Also related to #328 

This is especially weird for Shapes based on classes from web vocabularies, e.g. `http://www.w3.org/ns/Legal_entityShape` where the IRI namespace is hijacked.

**Comment by LadyMalande** [comment]
For now I am implementing the unique iri with the help of example.org, md5, technical label if present and a suffix whether it is NodeShape or PropertyShape. There is still some work to be done as md5 is now generated from the iri of the object. But that means that there is no distinction between different objects with the same iri. 

Work to be done to resolve this issue of same iri but different structure.

**Comment by jakubklimek** [comment]
Also, consider that there is already a setting for Base URL of the specification:
<img width="738" alt="image" src="https://github.com/mff-uk/dataspecer/assets/718827/2b45c82a-a1f7-4ab7-943d-d9221021b535">

**Comment by LadyMalande** [comment]
As of now, there is added support for baseURL usage in the IRI naming convention. 

The issue of different classes and the naming remains.

**Comment by LadyMalande** [comment]
If there is no baseURL specified, the IRIs for the shapes are relative now.

**Comment by LadyMalande** [comment]
The IRI of the generated shacl shapes are now tied to the psm of the given entity. That should help maintain the difference between different entities with the same cim but also should be the same every time for the same structure.
