### ISSUE TITLE
Why do Node shapes have labels and descriptions and Property shapes do not?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#330]
There is an inconsistency between how Node shapes and Property shapes are handled with respect to labels and properties, which are taken from the targetClass for Node shapes, but are missing in Property shapes (and could be also taken from the property label and description)

**Comment by LadyMalande** [comment]
Yes, that is true, thank you for your insight and check. 
Added sh:name and sh:description predicates to property shapes. Updated locally, will be pushed soon with other changes.

**Comment by LadyMalande** [comment]
If filled in, sh:name and sh:description are now generated in PropertyShapes. Closing the issue.
