### ISSUE TITLE
rdfs:label, rdfs:comment vs sh:name and sh:description

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#331]
Is there a reason that NodeShapes have `rdfs:label` and `rdfs:comment` instead of `sh:name` and sh:description` as described [in the specification](https://www.w3.org/TR/shacl/#name)?

**Comment by LadyMalande** [comment]
I believe it was swapped in the early stages of development for the sake of trying out attributes from different naming conventions and its availability. Other than that, there is no reason for the name and description to be swapped, so I will change it back to the original state. Thank you for the reminder.

**Comment by LadyMalande** [comment]
Issue solved by returning to sh:name and sh:description in the generator. Committed and pushed. Closing the issue.
