### ISSUE TITLE
Add support for typed/untyped instances in SHACL

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#339]
Based on #338 add support for untyped instances in SHACL. For untyped instances, it is not possible to rely on `sh:targetClass` as there will be no `<instance>rdf:type <class>` triple in the data. Shape nesting needs to be used instead.

**Comment by LadyMalande** [comment]
Added support for ALWAYS typed = targetClass, OPTIONAL + NEVER = focusing node through sh:targetObjectsOf, with the addition that NEVER has type in forbidden paths.

Need to resolve root untyped restrictions.

**Comment by jakubklimek** [comment]
Maybe a related thing, also maybe a new issue:
When you target according to type (in the always typed case), won't there also be an issue when have e.g. 
`Tourist attraction` as a root, then relation to e.g. `Owner`, and from owner a relation to other owned `Tourist attraction`s with a different contents? Won't the two shapes get mixed up?

**Comment by jakubklimek** [comment]
Regarding the untyped root, after a brief discussion with @sstenchlak we think it is OK not to support it at throw an error when there is no root type, as it seems like an edge case for our typical use cases and it does not make much sense to use SHACL when the root is not typed.

**Comment by LadyMalande** [comment]
Typed and untyped instances has been solved by adding sh:class for "ALWAYS" typed and adding not expecting rdf:type for "NEVER" options. "OPTIONAL" doesnt generate any constraint. Closing the issue. 
Typing instances option is also tied to SHACL targetting and has been tackled while working on the targetting issue as well.
