### ISSUE TITLE
StructureModelProperty.isReverse definition

### ISSUE THREAD

**Issue by LadyMalande** [mff-uk/dataspecer#346]
I have a question regarding the isReverse flag for StructureModelProperty class.

It "points" back to the parent of the parent class. 
Does it mean that:
1) The type (shape (attributes, configuration and other associations)) of the class type should be the same as the grandparent class - but the problem is, that you can add custom properties and associations to the reverse association regardless what the original class had under it.
**SHACL specific:** The reverse tag will set target class with the SAME NodeShape as was the grandparent.

2) The isReverse only says, that the class type IRI is the same for grandparent class AND the child node.
**SHACL specific:** The reverse tag will set the target class with constraints only regarding the <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, which will be the same as the grandparent.

**Comment by LadyMalande** [comment]
Example for case 1) here:
![obrazek](https://github.com/mff-uk/dataspecer/assets/42152093/7099f3b1-484b-4a2b-918b-a89dcd057f79)

**Comment by jakubklimek** [comment]
@LadyMalande The reverse tag only says, that in the RDF triples representing this relation, the subject and the object position is switched, nothing more. This is to account for the situation where the RDF predicate to be used to represent this nesting relation is defined in the opposite direction. It has no effect as to the types used. Structurally, the root digital object and the digital object to which the reverse association leads, are two different structures using the same class.

It is therefore not possible to validate this using SHACL class targeting. It needs to be validated using nesting of the SHACL shapes themselves. And for this case, SHACL supports [inverse property paths](https://www.w3.org/TR/shacl/#property-path-inverse).

**Comment by LadyMalande** [comment]
Inverse property paths added for SHACL and ShEx, closing the issue.
