### ISSUE TITLE
What does the number of items in Data structure represent?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#350]
I have 3 data structures - the first has 12 items, the last as 13 items:
<img width="925" alt="image" src="https://github.com/mff-uk/dataspecer/assets/718827/3da6d560-a5b4-46de-aa47-27e3442ff1fb">
Here is the first one (12 items):
<img width="905" alt="image" src="https://github.com/mff-uk/dataspecer/assets/718827/aaf06523-263f-49ea-9db6-351c4ac474e0">
And the second one (13 items):
<img width="904" alt="image" src="https://github.com/mff-uk/dataspecer/assets/718827/57e13c57-866f-48ef-aaca-402bef0701e9">
I do not see the difference.... In addition, in both cases, I actually see 7 items (nodes in the tree if that is what it is).

**Comment by sstenchlak** [comment]
It is the number of entities in the model, but that does not have to correspond to the real tree in the structure model. It will be removed/redone in the new manager.
