### ISSUE TITLE
"OR" interpretation causes wrong cardinalities to be present in conceptual diagram?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#367]
From [this specification](https://xn--slovnk-7va.gov.cz/generujeme/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F85cea4c0-4828-4e96-897f-1eb786256cee&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1700548651334-372a-8e50-b76e), a diagram is generated like this:
![image](https://github.com/mff-uk/dataspecer/assets/718827/7fc4290a-f831-4bfa-b18c-2a9014a9c41c)
Note the `1..*` cardinality of "creator". I am not sure how this happened. Here is the corresponding part of the data structure:
![image](https://github.com/mff-uk/dataspecer/assets/718827/2918d5bd-161c-48fc-81f5-b91abbd1fdd7)

**Comment by sstenchlak** [comment]
It has already been fixed, but old data may been corrupted. Please run garbage collection and automatic fixes for such problematic schemas.
![image](https://github.com/mff-uk/dataspecer/assets/23003372/22db5054-b700-428e-a4d6-490a441102c7)
