### ISSUE TITLE
Terms from external vocabularies cannot be updated when changed at source

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#373]
When a term is added from external, e.g. RDFS, vocabulary, and it is updated in the source vocabulary, there is no way of updating it in the local PIM.

**Comment by sstenchlak** [comment]
Already solved by "Update PIM" button.

**Comment by sstenchlak** [comment]
It should never happen automatically. You need full control over your specification and explicitly confirm to propagate any changes from outside the specification. The update PIM button is basically a very simple first version of evolution mechanism that checks what has changed and changes the specification accordingly. In the future, there will be an option to see the actual diff and choose what changes should be applied so I would not say it is a workaround. And yes, it would need to be re-implemented for v2.

**Comment by jakubklimek** [comment]
I agree. Therefore, if we close this for v1, another issue for v2 needs to be created, so that we know about this problem and can monitor how and when it will be tackled in v2.
