### ISSUE TITLE
Generated respec does not use custom templates from documentation configuration

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#399]
Generated respec does not use custom templates from documentation configuration.
E.g. [in this spec](https://xn--slovnk-7va.gov.cz/generujeme/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F10c501da-bd58-4bae-9fba-7672763249b7) the customized templates are ignored in the generated respec output.

**Comment by sstenchlak** [comment]
Fixed in 913b65a79706ba0741927e4f5bd6b1dbbc4e57ed
