### ISSUE TITLE
Generation of json-example does not work

### ISSUE THREAD

**Issue by LadyMalande** [mff-uk/dataspecer#420]
Since some commit, the json examples artifact does not generate output, instead throws an error from client generator.ts.

Is there any problem referencing the json-examples library?

**Comment by sstenchlak** [comment]
It works here https://tool.dataspecer.com/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F2203eabe-9807-47e9-8a95-4b7f1ae93267&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1655891975225-f581-8eed-bc80

Can you give me an example?

**Comment by LadyMalande** [comment]
https://tool.dataspecer.com/editor?data-specification=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F1ef6ae8e-53f5-4ed0-9021-e122fed28be7&data-psm-schema=https%3A%2F%2Fofn.gov.cz%2Fschema%2F1707267359524-5100-047c-992c
