### ISSUE TITLE
When there is only one data structure in data specification, subfolder not necessary

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#423]
When there is just one data structure in a specification, which is quite common, a separate folder for it is not necessary.
![image](https://github.com/mff-uk/dataspecer/assets/718827/32acb964-da4a-428c-9c98-1040d7c71c14)

i.e. all files could be in `datove-sady-publikujici-udaje` directly, not under `verejny-udaj`.

**Comment by sstenchlak** [comment]
There is an option to turn this behavior off. By default it is on.

![image](https://github.com/mff-uk/dataspecer/assets/23003372/13a11764-aa74-44cb-a25a-540c5fc926d8)
