### ISSUE TITLE
Add support for custom naming of files with artifacts

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#424]
Currently, file names of generated artifacts are fixed - `context.jsonld`, `example.json`, `schema.json` etc.
However, for Czech specifications, this is limiting and the files need to be renamed and relinked manually.

Part of the configuration should be support for naming the output files.
This may be also connected to customizing paths to the files (#423 #422), i.e. `./schémata/schéma.json` etc.

This would also enable us to name the doc file `index.html` instead of `documentation.html`

**Comment by jakubklimek** [comment]
Related to #423 and #422 - the first iteration could be to allow to manually fill in path + file name for each generated artifact/file as an override to the default behavior.

**Comment by sstenchlak** [comment]
You can now change the last part of the file name for every artifact. Together with #423 and #422, it should be sufficient for most of our use cases.

Artifacts that are disabled have no option to change their name.

Please keep in mind that **the name** of some artifact is the name of the directory. For example `rdf-to-csv/` or `LDkit/`.

![image](https://github.com/mff-uk/dataspecer/assets/23003372/e02d0040-6f02-49d5-99fe-a8f64380b476)
