### ISSUE TITLE
`$id` missing in JSON Schema

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#425]
Typically, JSON Schemas contain an `$id` value with URL of the schema. Once this is known, it should be filled in the JSON Schema.

Related to #337

**Comment by sstenchlak** [comment]
Hi, now the `$id` is generated always. If you specify the public URL of the data specification, then the `$id` would match the URL address of the schema itself.

I think it is not a problem that the `$id` is generated even if the specification has no public URL, but it can be removed if you want.

Also, my understanding was that the `$id` should match the file location, which is obtained as a concatenation of the public URL and physical location in the generated ZIP file relative to the specification root.
