### ISSUE TITLE
Weird attribute names in the class detail

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#442]
When I open the detail of a class with attributes, there is a weird '@' in the end of the name of each attribute in the attributes list:

![image](https://github.com/mff-uk/dataspecer/assets/4235208/c8d82dee-c29e-42f3-ba5f-6bca90a21e49)

There should be just a name of each attribute.

**Comment by jakubklimek** [comment]
Probably a language tag separator?
