### ISSUE TITLE
Impossible to edit attributes of a class

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#444]
I do not see how to edit an attribute. 

If I have the detail or edit of a class, I can just see the attributes (and delete them in the edit dialog). However, I cannot edit them.

If I go to the attributes tab in the model browser on the right, I see the edit button but when I click on it, I see an edit dialog for something else than the attribute:

<img width="1644" alt="image" src="https://github.com/mff-uk/dataspecer/assets/4235208/c649cb96-3b08-4615-9bba-c4624e0c5388">

**Comment by apolicky** [comment]
Fixed by one of the previous pull requests
