### ISSUE TITLE
When single-clicking into blank space on canvas, add new class and add it to current view

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#446]
The only way to add a class is currently through the explorer on the left.
It would be nice if I could add a class by clicking into blank space on canvas.

**Comment by apolicky** [comment]
Works with `alt+Click` on the canvas
![image](https://github.com/mff-uk/dataspecer/assets/42609304/569a2582-5aa6-4bd5-9d1c-956da7056b4d)
