### ISSUE TITLE
Domain and range in OWL output swapped

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#474]
In the OWL output from the conceptual model editor, the domain and range of the output properties are swapped. The source class (for attributes and relationships) is in the rdfs:range, the target (for relationships) is in the rdfs:domain.

**Comment by sstenchlak** [comment]
Can you provide more detail? Cannot replicate.

**Comment by apolicky** [comment]
Whoops, should be fixed by #475
