### ISSUE TITLE
`*..*` cardinality

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#485]
See [this spec](https://feature-dscme-profile-iris.dataspecer.pages.dev/conceptual-model-editor/core-v2?package-id=0df4e771-8f5f-4faf-a30a-d48c7f799f51&view-id=00bec4b8-f5fd-4f8f-897c-1fd9a796caa2%2Fvisualization). I added Dataset and Catalog from DCAT. It includes relations with `*..*` cardinality, which makes no sense:
![image](https://github.com/mff-uk/dataspecer/assets/718827/d455f600-7917-4040-a577-cab76d862f0a)
Not sure whether this is a CME or RDFS import bug.

**Comment by apolicky** [comment]
The object for `dataset` relationship dscme receives from aggregator looks as follows:
```json
{
    "id": "http://www.w3.org/ns/dcat#dataset",
    "iri": null,
    "type": ["relationship"],
    "name": {...},
    "description": {...},
    "ends": [
        {
            "cardinality": [null,null],
            "name": {},
            "description": {},
            "concept": "http://www.w3.org/ns/dcat#Catalog"
        },
        {
            "cardinality": [null, null],
            "name": {...},
            "description": {...},
            "concept": "http://www.w3.org/ns/dcat#Dataset",
            "iri": "http://www.w3.org/ns/dcat#dataset"
        }
    ]
}
```
Cardinality `[null,null]` is then displayed as `*..*`. The value `[null,null]` can be displayed differently, but it seems that the cardinality value shouldn't be passed to dscme

**Comment by sstenchlak** [comment]
https://tool.dataspecer.com/conceptual-model-editor/core-v2?package-id=0df4e771-8f5f-4faf-a30a-d48c7f799f51&view-id=00bec4b8-f5fd-4f8f-897c-1fd9a796caa2%2Fvisualization

**Comment by jakubklimek** [comment]
Not sure if I need to re-create something, but for the profile relation, I still see `*..*`:
![image](https://github.com/mff-uk/dataspecer/assets/718827/5b2a46d2-2e2d-4553-ac35-9d05fbdffea1)

**Comment by jakubklimek** [comment]
@apolicky There is still need to remove this option from dialogs.
