### ISSUE TITLE
Add support for CLI

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/dataspecer#49]
We need to be able to bundle and execute the transformers using command lined interface.

**Comment by sstenchlak** [comment]
Could you please be more specific about this? #45 wasn't documented well enough, but by running `npm run build`, the tarball is created in the `dist` directory, which can be installed in a client code by running `npm install <path to tarball>`.

**Comment by skodapetr** [comment]
The main objective is to be able to run something like:
```npm run model-driven-data object-model ./object-model.json respec ./output-directory/``` or ```model-driven-data object-model ./object-model.json respec ./output-directory/```. The difference does not really matter now, it should be related to the ```npm install``` as you mentioned. 

Before this it will be probably necessary to process TypeScript code into JS so it can be executed using node.

**Comment by sstenchlak** [comment]
Basic CLI functionality is already implemented.
