### ISSUE TITLE
SPARQL loader

### ISSUE THREAD

**Issue by sstenchlak** [mff-uk/dataspecer#51]
The goal is to implement a Webpack loader for `*.sparql` files that minimizes and transforms them into a parametrized function replacing the template variables inside them.

**Comment by skodapetr** [comment]
@sstenchlak  Is this resolved by the PR?

**Comment by sstenchlak** [comment]
Not yet. I'm implementing it next week.

**Comment by sstenchlak** [comment]
Sorry for the inactivity. Reimplementing a build mechanism of the core library will resolve this issue.

**Comment by sstenchlak** [comment]
This issue is finally resolved in 47f9b75fe662c075b7748a476e393d2f37a6bacd by implementing custom transpiler compatible with Jest transformers. SPARQL queries are optimized, converted to functions and saved as .js files alongside tsc transpiled files.
