### ISSUE TITLE
conceptual-model-editor and project-manager

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/dataspecer#510]
Is there still a need to have a [project-manager](https://github.com/mff-uk/dataspecer/tree/main/applications/conceptual-model-editor/src/app/project-manager) as a part of the conceptual-model-editor?

**Comment by sstenchlak** [comment]
There are still some todos on my side to implement, such as propagation of model name into conceptual-model-editor application, but in general the project-manager part can now be removed in favor of the manager app.
