### ISSUE TITLE
Hide model GUID when creating class

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#533]
This is when I create my first class:
![image](https://github.com/mff-uk/dataspecer/assets/718827/4cd3510c-ad9b-469e-b0f3-214c85b22bde)

The GUID should not be visible.

**Comment by skodapetr** [comment]
Should be already solved as part of another issue, where the way we generate labesl was changed.
At the same time, if the model has no alias the ID with addional message will be sivible.
