### ISSUE TITLE
Generalizations do not need external IRIs

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#537]
Here, I need to choose one, but this should not be necessary as they are represented using rdfs:subClassOf and rdfs:subPropertyOf
![image](https://github.com/mff-uk/dataspecer/assets/718827/522d6321-a891-4329-9826-fa33fd69ae07)

**Comment by skodapetr** [comment]
@jakubklimek  So the idea is to hide the input box and use null instead?

**Comment by jakubklimek** [comment]
Yes. Currently, I see no case for having a public IRI of the generalization, since it is represented by the `rdfs:subClassOf` predicate, not by IRI in RDF based vocabularies.
