### ISSUE TITLE
Why is there "es" language when no "es" language was used?

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#538]
I used only english (default) and "cs" langs, yet, there is "es" lang offered:
![image](https://github.com/mff-uk/dataspecer/assets/718827/db9b6ddc-95f2-472e-9639-d29a4e6b1091)

**Comment by skodapetr** [comment]
It was predefined in the `configuration-context` class. Now we have only `cs` and `en` as defaults.
