### ISSUE TITLE
Name imported models better

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#539]
Now when I import SKOS from `https://datagov-cz.github.io/cache-slovniku/skos.rdf`, the model is named using a random string. I would expect it to be named `skos` if available. The rules could be
1. the file name without extension, when the URL ends with a filename.
2. the last word before `#` or `/`, e.g. for `http://www.w3.org/ns/dcat#` it would be `dcat`
3. random otherwise

**Comment by jakubklimek** [comment]
related to https://github.com/mff-uk/dataspecer/issues/575

**Comment by skodapetr** [comment]
The UI has been change to single URL import, the interface to backend is [here](https://github.com/mff-uk/dataspecer/blob/main/applications/conceptual-model-editor/src/app/diagram/catalog/model-catalog.tsx#L40).

Now we need to update backend to set alias based on the URL.
