### ISSUE TITLE
Support for prefixes

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#540]
It would be nice to somehow support prefixes to make the diagram more readable:
![image](https://github.com/mff-uk/dataspecer/assets/718827/22fb0194-25fc-49d8-aa2c-d33c2995084e)

It could be either prefix.cc, or/and manual table somewhere.

**Comment by skodapetr** [comment]
We decided to employ an "API" compatible with prefix.cc service to get prefixes.

**Comment by jakubklimek** [comment]
@sstenchlak Do you already know how to handle prefixes systematically?

**Comment by skodapetr** [comment]
A dirty solution using predefined table of prefixed is implemented in https://github.com/mff-uk/dataspecer/commit/c4991fccf24d496822ee0b9af6f3986d518b3bf9 .

The biggest chalange is going to be to obtain this list upfront, not on-demand when rendering the items.
