### ISSUE TITLE
Export of specification should be more visible

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#551]
![image](https://github.com/mff-uk/dataspecer/assets/718827/2fcbb79e-15b6-4dff-bac4-96b50a099b78)

Currently, it is not clear that "...", "Export" is export of the specificaiton, and not e.g. a download of the whole package, which would also make sense.

I suggest renaming the option to "Export specification".
It may also be necessary to split it into 2 - Export vocabulary specification and Export application profile specification.

**Comment by sstenchlak** [comment]
Type of generated ZIP file depends on the configuration, hence I would prefer one button.
