### ISSUE TITLE
Attribute profile domain, Relationship profile domain and range should be only ClassProfiles, not Classes

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#583]
Currently, classes and class profiles can be used:
![image](https://github.com/mff-uk/dataspecer/assets/718827/642cb431-e67e-4efb-b8eb-a9178fdde7e6)

**Comment by skodapetr** [comment]
@jakubklimek But then you would not be able to create an attribute or an association for a vocabulary?

You would neet to define a class, define a default profile of the class and then create an association between the default profiles and then create default profile for the association again ... ?

**Comment by jakubklimek** [comment]
Sorry, missing "profile" in the title. Attribute profile and relationship profile can have only class profile as a domain/range.
