### ISSUE TITLE
Attribute profiles have "range cardinality" hidden sometimes

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#588]
Interestingly, this happens for `dcterms:title`and not for `dcterms:description`:
title:
![image](https://github.com/mff-uk/dataspecer/assets/718827/738e73d1-8c07-4c6e-984a-70d84a65eb4a)

description:
![image](https://github.com/mff-uk/dataspecer/assets/718827/c4ecfdf6-29da-4e46-818e-5bbe3bd6b529)

**Comment by skodapetr** [comment]
@jakubklimek  Do you have a model where I can reproduce?

Also not sure about the issue as the main difference is missing range cardinality.
The range cardinality should be visible only, when range is set to something.

**Comment by jakubklimek** [comment]
This is probably connected to #584 - In [this model](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=8e4666aa-190e-4755-9e65-334bb7df7e4a&view-id=6ce36e30-b0b5-41c6-b54d-865ab3e40c36), when you try to create profile of Title attribute and Description attribute, in both cases there is no range visible, but in one case, range cardinality is visible (for title, which actually has the rdfs:Literal range in the source).
This could mean that the range is in fact set to something - rdfs:Literal? - but not visible in the dialog.

**Comment by jakubklimek** [comment]
You can reproduce [here](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=8babab56-faea-4fb7-982b-595a60b4489f&view-id=e7e7aa7c-d0f2-4374-8fb6-ee5b46c9ee20) when profiling dcterms:description
![rel prof range missing](https://github.com/mff-uk/dataspecer/assets/718827/fb169027-8915-4e25-a068-7eacb6097c47)
