### ISSUE TITLE
Moving attribute profiles from class profile to class profile does not sync correctly

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#590]
When an attribute profile domain is changed, it appears in the new position, but does not disappear from the old one:
![image](https://github.com/mff-uk/dataspecer/assets/718827/95cbcd95-8770-433d-bcf3-a2780967bb16)
after reload
![image](https://github.com/mff-uk/dataspecer/assets/718827/583519e8-fe01-498d-9a89-1e120b251cf4)

**Comment by sstenchlak** [comment]
Same issue inside vocabulary. Just try to move an attribute.

**Comment by skodapetr** [comment]
As the whole view is reloaded on any model change, due to changesin contexts, this functionality is not in its file form. Yet it seems to work now as intended.
