### ISSUE TITLE
Allow editing of documentation base URL and base IRI

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#611]
When I enter these two on specification creation:
![image](https://github.com/mff-uk/dataspecer/assets/718827/040e9534-83c4-4232-96c4-e33f13f1f2c1)

there is no way to change them. I would have to re-create the whole specification/vocabulary.
It is therefore necessary to be able to edit them. And also in the already imported specifications.

This means that when I point to e.g. DCAT and create an AP of it, in the documentation of the AP, this URL should be used for generating links to the DCAT documentation (#610).
I should be therefore able to change it even then, i.e. for DCAT in here:
![image](https://github.com/mff-uk/dataspecer/assets/718827/f0f71204-ef71-4f5f-bbe4-ce9d76e88775)

I suggest to reuse the "Rename the resource" dialog for that, and change it to "Edit the package"

**Comment by sstenchlak** [comment]
Base IRI can be changed in the conceptual model editor where it belongs and we discussed not to use base URL for documentation.
