### ISSUE TITLE
Make autosave on by default

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#614]
Autosave is off by default. But this is not an expected behavior from a modern web app.

Yes, I just lost an entire vocabulary because this was not on, I forgot to click on save package, and I did an F5 refresh to get a new dataspecer version...
![image](https://github.com/mff-uk/dataspecer/assets/718827/d1afef98-cbd2-433c-ab15-fa77a9341463)

**Comment by skodapetr** [comment]
Just keep in mind, that autosave is triggered in a predefined interval, 15 seconds by default. The interval can be changed in the .env file.
