### ISSUE TITLE
Add model aliases to all domains, ranges and generalization comboboxes, sort by name

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#616]
Currently, it is very frustrating to find the correct thing in the comboboxes as they are not sorted, and all terms are mixed from all models (and this is without APs):
![image](https://github.com/mff-uk/dataspecer/assets/718827/5ca84072-3d26-4adb-911e-c698df79df48)

**Comment by skodapetr** [comment]
@jakubklimek  Next time please provide screenshot where the whole dialog is visible as from this one it is not clear which dialog it is.
