### ISSUE TITLE
Allow user to set profile property to its inherited value

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#625]
In [this spec](https://iswc2024.dataspecer.com/conceptual-model-editor/diagram?package-id=0771429e-864a-4067-8015-6f3fbd6b2889&view-id=03fd7bc9-7256-479d-b6f1-6efe9327543f) (note it is the iswc2024 instance) I cannot set the Publisher relationship profile range to Agent (DCAT-DAP).
![rel prof range](https://github.com/mff-uk/dataspecer/assets/718827/44682478-2018-459a-8cd3-75fedeb6f8b7)

**Comment by skodapetr** [comment]
The "change in profile" checkbox is not preserved (open / close dialog) when the default (inherited) value is not changed.

**Comment by skodapetr** [comment]
It seems that this behavious is by design, yet it should be different. 
Once user select "override" the default value should be set in this profile. 

The inheritance should be detected by the null value of the properties at the entity.

**Comment by jakubklimek** [comment]
This still seems broken, I am not able to keep the value "unchecked" [here](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=3fd454be-cf05-4d83-a041-60491234b178&view-id=40f8aa23-376a-42c7-ba5e-7dd03ef0b814):
![change in profile](https://github.com/user-attachments/assets/5454c9b2-9923-48ee-bcdf-aca2f1c731d2)

**Comment by jakubklimek** [comment]
Probably duplicate of #782, so closing this one even though not resolved yet.
