### ISSUE TITLE
Cardinalities missing in application profile documentation

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#628]
Cardinalities are currently not reflected in the Respec documentation at all. They need to be added.

**Comment by jakubklimek** [comment]
I updated the template for DSV-AP in https://tool.dataspecer.com/manager/ but I still do not see the cardinalities.

**Comment by sstenchlak** [comment]
It seems that you accidentally wrongly merged your changes with the original template. It works now in https://backend.dataspecer.com/preview/en/index.html?iri=3fd454be-cf05-4d83-a041-60491234b178
