### ISSUE TITLE
Context menu is not closed when another one is opened

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#633]
![image](https://github.com/mff-uk/dataspecer/assets/718827/1d655130-c96c-4861-8e18-41360819f1af)

After clicking elsewhere, only the last one is closed. The other ones are stuck.
![image](https://github.com/mff-uk/dataspecer/assets/718827/ce4073d3-4c48-407f-a322-13dc3779a1e9)

Thanks @RadStr

**Comment by skodapetr** [comment]
This context menu has been removed.
