### ISSUE TITLE
Consider migrating Reactflow to new version (v11 -> v12)

### ISSUE THREAD

**Issue by RadStr** [mff-uk/dataspecer#657]
At the start of july Reactflow v12 was oficially released. It might be beneficial to migrate to the newer version for future development.
You can read more about the version in the [blog post](https://reactflow.dev/whats-new/2024-07-09).

### Features

- Light/Dark mode - More of a starting point than complete solution 
- [ViewportPortal](https://reactflow.dev/api-reference/components/viewport-portal) component which allows putting stuff (Text, lines, etc.) on canvas at certain absolute position. This might useful for example for implementation of [helper lines](https://reactflow.dev/examples/interaction/helper-lines).
- Better TS docs
- Changes to how width/height of nodes behaves
- New helper functions
- and some more (for example SSR), which I am not sure about usefulness for our specific use case
- Maybe better performance for large diagrams

### Drawbacks

Main drawback is that v12 is not backwards compatible with v11, but the migration should be relatively painless, especially since the reactflow isn't yet heavily utilized in the project. We just use simple rendering and custom nodes and edges. The blogpost explaining migration can be found [here](https://reactflow.dev/learn/troubleshooting/migrate-to-v12).

- I hope that there are no other hidden drawbacks.

### Who will do it

If we decide to migrate, then we can later discuss who us two should do it.

**Comment by skodapetr** [comment]
We are now using version 12.3.4.
