### ISSUE TITLE
CoreResourceReader query

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/dataspecer#66]
We need to be able to query ```CoreResourceReader``` for resources with particular interpretation or ends of the association.  
Possibilities are:
 * Return all resources with arbitrary predicate and object of given value
 * Let user specify RDF predicate and object
 * Let user query by example using model objects

**Comment by sstenchlak** [comment]
Resolved by introducing a concept of views.

See https://github.com/mff-uk/dataspecer/blob/e541a496d9721cb650e0d03ee05d082e750ad0b6/packages/core-v2/src/semantic-model/async-queryable/queries.ts#L8
