### ISSUE TITLE
SPARQL dotazy - výběr prvku pomocí FILTER

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#77]
V dotazech se prvek (např. třída) vybírá přes FILTER (?node = %NODE%), např.:

https://github.com/opendata-mvcr/model-driven-data/blob/4f59ba29921ea0023996a7b4c40ef896cd3c97dc/lib/sgov/queries/get-class.sparql#L21

Nebylo by lepší to udělat přes VALUES ?node { %NODE% }?

Případně rovnou všude místo ?node dát %NODE%?

**Comment by sstenchlak** [comment]
Měl jsem problém s tím, že EXISTS funguje jinak, než jsem čekal a přiznám se, že se mi to tehda nechtělo moc řešit, tak jsem zůstal u toho co mám teď, protože to fungovalo.

Níže je jednoduchý příklad těch tvou variant, kdy každá vrací jiné výsledky.
```sparql
DEFINE sql:signal-void-variables 0

PREFIX z: <https://slovník.gov.cz/základní/pojem/>

CONSTRUCT {
  <https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl> <__is_ciselnik> ?is_ciselnik .
} WHERE {
  <https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl> a z:typ-objektu .
  BIND(EXISTS {<https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl> rdfs:subClassOf+ <https://slovník.gov.cz/datový/číselníky/pojem/položka-číselníku>} as ?is_ciselnik)
}
```
```sparql
DEFINE sql:signal-void-variables 0

PREFIX z: <https://slovník.gov.cz/základní/pojem/>

CONSTRUCT {
  ?node <__is_ciselnik> ?is_ciselnik .
} WHERE {
  ?node a z:typ-objektu .
  BIND(EXISTS {?node rdfs:subClassOf+ <https://slovník.gov.cz/datový/číselníky/pojem/položka-číselníku>} as ?is_ciselnik)
  FILTER (?node = <https://slovník.gov.cz/datový/turistické-cíle/pojem/turistický-cíl>)
}
```

Když odstraním první řádek, tak dostávám `Virtuoso 37000 Error SP031: SPARQL compiler: The list of return values contains '*' but the pattern does not contain variables`. Kdybyste měli (@jakubklimek @martinnec) čas mě navést v tomto správným směrem, tak budu rád.
