### ISSUE TITLE
Profiles are created in the wrong vocabulary by default

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#774]
When I create a class profile, it is created in the model (vocabulary) of the class instead of the current "main" vocabulary. Interestingly, this is not the case for the other vocabularies, just the "2024-11-07 DCAT" one:
![{25B96E84-62AC-4A1D-8D75-978F5BFE368D}](https://github.com/user-attachments/assets/6e6fa7b6-85b6-4ca6-9197-2a603841154e)

From video:
![{3FF6F3D1-484F-4CDF-B609-35BD0E27C179}](https://github.com/user-attachments/assets/8c8fc4a3-d844-4fa6-bcee-82a07659fd0b)

**Comment by skodapetr** [comment]
More details are needed to reproduce.
Linke to a project.
Details on how did you created the vocabularies.
