### ISSUE TITLE
"Entity is not part of the visual model" is a weird message to get on delete

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#776]
![{9C533342-0E6B-4DCE-A98F-2DBCA7D9AF32}](https://github.com/user-attachments/assets/4eabd922-367e-4a9e-b5f6-db135a243526)

It is a bit unexpected. I would expect something like "deleted", if at all. Like this, I am not sure if it actually shows and error with a green tick or what is going on as we do not have these for other operations.

**Comment by skodapetr** [comment]
Well it is actually an error/warning. The problem is that we remove the entities one after another at the same time removal of the node cause automatic removal of the edges causing this message. A temporary solution is to disable the message, should be good enough for now.
