### ISSUE TITLE
Inconsistency in attribute profile dialog

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#778]
When editing attribute profiles, only class profiles are offered as Domains:
![{72D4B44C-3CBC-44BE-95B9-DF006281A257}](https://github.com/user-attachments/assets/cd6c6133-973f-4d7f-b96f-e86d46b382b9)
However, when creating profiles, both profiles and classes are offered as domains:
![{947653D7-76C4-4CE0-A678-82BE27792185}](https://github.com/user-attachments/assets/269b7c23-4864-450b-bad2-92f02d8cc3e2)

It should be only class profiles.

**Comment by skodapetr** [comment]
@jakubklimek Is this still valid? Perhaps solved as part of  https://github.com/mff-uk/dataspecer/issues/780 ?

**Comment by jakubklimek** [comment]
Yep
