### ISSUE TITLE
Cannot set "change in profile" - it is not saved

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#782]
In [this spec](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=3a8cb245-0da1-4485-b9f9-b699927dab70&view-id=62b9f8f4-68c9-40cb-8cb9-872b06fafcbe)
![{9441D658-F594-4983-9A32-6D44BB72E76D}](https://github.com/user-attachments/assets/e9b06607-b261-45d2-94d1-f728e8db9fa4)
Name is not changed here, however, this information is missing in the DSV:

```turtle
<https://example.org/dcat-dap#dct-title> dsv:domain <https://example.org/dcat-dap#Resource>;
    dct:isPartOf <https://example.org/dcat-dap#applicationProfileConceptualModel>;
    a dsv:Profile;
    dsv:inheritsProperties <http://purl.org/vocab/vann/usageNote>;
    dsv:cardinality <https://w3id.org/dsv#1n>;
    dsv:property <http://purl.org/dc/terms/title#attribute>;
    a dsv:DatatypePropertyProfile.
```
resulting in bad name in doc:

![{89E34E29-0A1E-45E9-9D00-E30356E664D6}](https://github.com/user-attachments/assets/529d4be9-c33e-46ce-ba1f-c5ae8fb22c79)

**Comment by jakubklimek** [comment]
Actually, this is a broader issue than originally expected. I cannot see "change in profile" for attribute profiles names, definitions (maybe also elsewhere):
![dialog](https://github.com/user-attachments/assets/57e72542-8de4-4552-9ff1-558a33f6929b)

**Comment by skodapetr** [comment]
Perhaps duplicit to https://github.com/mff-uk/dataspecer/issues/625 ?

**Comment by jakubklimek** [comment]
Still not fixed. When I change the title and do "change in profile", it is changed and applied. However, upon reopening the dialog, the checkbox is not checked. Consequently, I cannot "disable" overriding the title in the profile.
