### ISSUE TITLE
Lists of profiled things in documentation

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#789]
In [this spec](https://backend.dataspecer.com/preview/en/index.html?iri=c0d97703-fcdb-4099-b247-eea13eb90115), in "Profiles" - all classes and profiles in the profile hierarchy are apparently listed, which is unexpected. Only the immediate profiled class/profile should be listed.

![image](https://github.com/user-attachments/assets/161d8bda-a57d-40cb-b964-e53dbd8eac22)

At the same time, it would be useful to see the actual class/property at the end of the profiling hierarchy, as a separate item.

If it was an intention to list all the items on the profiling hierarchy (which could be also useful), then it should be displayed in a way that conveys the hierarchy, i.e. not just a list, but maybe `>` separated inline list? E.g. `Dataset (DCAT-DAP) > Dataset (DCAT)`

**Comment by sstenchlak** [comment]
I tried several ways and the following one seemed the least bad to me.
<img width="615" alt="{B6896526-4A57-4CB0-81B7-B7C92288953D}" src="https://github.com/user-attachments/assets/0b090a08-9036-4383-9b2b-955959cb3150">
