### ISSUE TITLE
Semantic models in new packages not named on "demo" instance

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#794]
![image](https://github.com/user-attachments/assets/5df3432c-10c8-4559-bd7f-915ca62b6926)
They are just named "Semantic model"

**Comment by sstenchlak** [comment]
I am unable to replicate this. Project Wizard -> Vocabulary creates the semantic model with the name provided in the form.

**Comment by sstenchlak** [comment]
After further discussion, we concluded that this was probably caused by a browser cache as I could not replicate the problem.
