### ISSUE TITLE
DCAT can't be added in CME on other than main branch instance

### ISSUE THREAD

**Issue by RadStr** [mff-uk/dataspecer#831]
- On dataspecer's main branch there is no issue.
- When I am on other than main branch instance of dataspecer (main meaning https://tool.dataspecer.com/), I can't add DCAT from well-known vocabularies.
- The issue is because of missing CORS header - see example later
- I created GitHub issue, but maybe it isn't that important? 

### Example:

1. I am on https://stable.dataspecer.pages.dev/conceptual-model-editor/diagram
2. I try to add DCAT
3. I get error in console: (Důvod: chybí hlavička CORS ‘Access-Control-Allow-Origin‘). Stavový kód: 302.
![firefox_TZcWJO0xxE](https://github.com/user-attachments/assets/7aa56e6f-07d4-4193-bc75-183297e2ef78)

**Comment by jakubklimek** [comment]
This was fixed in `main` , see #815
