### ISSUE TITLE
Schema generators must generate IRI item for a PSM class

### ISSUE THREAD

**Issue by martinnec** [mff-uk/dataspecer#94]
For each PSM class, the IRI item needs to be generated in a schema.

For JSON schema, it is easy, it shall be

```json
"iri": {
  "type": "string",
  "format": "iri"
}
```

For XML schema, shall we have 

`<xs:element name="iri" type="xs:anyURI"/>`

or

`<xs:attribute name="iri" type="xs:anyURI"/>`

or something else?

**Comment by jakubklimek** [comment]
I would stick to https://ofn.gov.cz/základní-datové-typy/2020-07-01/#url , which is the type of "Věc" in current FOSes. I.e. XML element, not attribute.

**Comment by martinnec** [comment]
I agree.

**Comment by cermakmarek** [comment]
How should the `<iri>` element interact with namespaces? Should it be placed in the same namespace as the element (taken from the XML PSM extension for the schema), should it be in the unnamed default namespace (`xmlns=""`), or should there be a specific namespace used exclusively by the element?

**Comment by jakubklimek** [comment]
This is a good question.
1. I would avoid using unqualified names (no namespace)
2. In the original OFNs, we actually had the IRI as a regular property of Thing, inherited almost everywhere. Then it would belong to the targetNamespace of the Thing schema.
3. If we view the IRI as a special artifact of our approach, then it should be in a separate "technical" namespace.

Currently, I am leaning towards 3. as even entities not inheriting from Thing should be identifiable. Identification of entities is independent on the inheritance relations.

**Comment by cermakmarek** [comment]
I agree; this will also make it possible to define properties with the name `iri` freely. In that case, we will need a namespace IRI to place it in, and a schema available somewhere, since the generated XML Schema will have to import it:
```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="our namespace"> 
    <xs:element name="iri" type="xs:anyURI"/>
</xs:schema>
```

**Comment by jakubklimek** [comment]
How about `https://schemas.dataspecer.com/xsd/core/<version_date>` @sstenchlak ? Other suggestions welcome. Examples e.g. in https://github.com/opendata-mvcr/otevrene-formalni-normy/blob/7e3c7d33a2fada50ddcb062faaa97de04864c624/kontakty/2020-07-01/sch%C3%A9mata/kontakt.xsd

**Comment by cermakmarek** [comment]
The `langString` type used for OFN Text type should also be defined in this schema, i.e.
```xml
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:complexType name="langString">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
```
At the moment, this type is defined in every schema that uses it.

**Comment by cermakmarek** [comment]
I used `https://schemas.dataspecer.com/xsd/core/` and `https://schemas.dataspecer.com/xsd/core/2022.xsd` when writing the examples on the web, so I am fine with a URI like that, but we need the XSD somewhere @sstenchlak

**Comment by sstenchlak** [comment]
I am okay with the URI format proposed by @jakubklimek. The schemas themselves can be in the corresponding subfolder in the `schemas` directory at the root of this repository.

**Comment by jakubklimek** [comment]
This is resolved. Only support for CSV remains, which is a separate issue #189
